import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`_users_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_users_v\` ADD \`published_locale\` text;`)
  await db.run(sql`CREATE INDEX \`_users_v_snapshot_idx\` ON \`_users_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_users_v_published_locale_idx\` ON \`_users_v\` (\`published_locale\`);`)
  await db.run(sql`ALTER TABLE \`_agents_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_agents_v\` ADD \`published_locale\` text;`)
  await db.run(sql`CREATE INDEX \`_agents_v_snapshot_idx\` ON \`_agents_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_agents_v_published_locale_idx\` ON \`_agents_v\` (\`published_locale\`);`)
  await db.run(sql`ALTER TABLE \`_media_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_media_v\` ADD \`published_locale\` text;`)
  await db.run(sql`CREATE INDEX \`_media_v_snapshot_idx\` ON \`_media_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_media_v_published_locale_idx\` ON \`_media_v\` (\`published_locale\`);`)
  await db.run(sql`ALTER TABLE \`_notes_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_notes_v\` ADD \`published_locale\` text;`)
  await db.run(sql`CREATE INDEX \`_notes_v_snapshot_idx\` ON \`_notes_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_notes_v_published_locale_idx\` ON \`_notes_v\` (\`published_locale\`);`)
  await db.run(sql`ALTER TABLE \`_note_tags_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_note_tags_v\` ADD \`published_locale\` text;`)
  await db.run(sql`CREATE INDEX \`_note_tags_v_snapshot_idx\` ON \`_note_tags_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_note_tags_v_published_locale_idx\` ON \`_note_tags_v\` (\`published_locale\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX IF EXISTS \`_users_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_users_v_published_locale_idx\`;`)
  await db.run(sql`ALTER TABLE \`_users_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_users_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_agents_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_agents_v_published_locale_idx\`;`)
  await db.run(sql`ALTER TABLE \`_agents_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_agents_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_media_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_media_v_published_locale_idx\`;`)
  await db.run(sql`ALTER TABLE \`_media_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_media_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_notes_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_notes_v_published_locale_idx\`;`)
  await db.run(sql`ALTER TABLE \`_notes_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_notes_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_note_tags_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`_note_tags_v_published_locale_idx\`;`)
  await db.run(sql`ALTER TABLE \`_note_tags_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_note_tags_v\` DROP COLUMN \`published_locale\`;`)
}
